### ISSUE TITLE
Tests failing with expected 5月后 and actual 4月后

### ISSUE THREAD

**Issue by niklasf** [hustcc/timeago.js#143]
Some tests are failing with what looks like off by one errors, for example:

```
Locale testcase for [zh_CN]
[...]
ok 1312 should be equal
ok 1313 should be equal
ok 1314 should be equal
not ok 1315 should be equal
  ---
    operator: equal
    expected: '5月后'
    actual:   '4月后'
    at: module.exports (/home/niklas/Projekte/timeago.js/tests/locales/zh_CN.js:52:5)
    stack: |-
      Error: should be equal
          at Test.assert [as _assert] (/home/niklas/Projekte/timeago.js/node_modules/tape/lib/test.js:212:54)
          at Test.bound [as _assert] (/home/niklas/Projekte/timeago.js/node_modules/tape/lib/test.js:64:32)
          at Test.equal.Test.equals.Test.isEqual.Test.is.Test.strictEqual.Test.strictEquals (/home/niklas/Projekte/timeago.js/node_modules/tape/lib/test.js:347:10)
          at Test.bound [as equal] (/home/niklas/Projekte/timeago.js/node_modules/tape/lib/test.js:64:32)
          at module.exports (/home/niklas/Projekte/timeago.js/tests/locales/zh_CN.js:52:5)
          at files.forEach.file (/home/niklas/Projekte/timeago.js/tests/test.js:18:37)
          at Array.forEach (<anonymous>)
          at fs.readdir (/home/niklas/Projekte/timeago.js/tests/test.js:13:11)
          at FSReqWrap.oncomplete (fs.js:149:15)
  ...
ok 1316 should be equal
ok 1317 should be equal
ok 1318 should be equal
[...]
```

Seems to be always in the

```javascript
t.equal(tb.addMonths(5), '....');
```

test case.

**Comment by hustcc** [comment]
You can write some demo code to debug it.

The problem can not appear on my pc.

Thank you~

**Comment by niklasf** [comment]
Oh, intresting. I will try on more machines and see if I can make it reproducible.

**Comment by niklasf** [comment]
Turns out the test failure is timezone dependent.

Passing:

```
export TZ=/usr/share/zoneinfo/UTC
export TZ=/usr/share/zoneinfo/Asia/Seoul
```

Failing:

```
export TZ=/usr/share/zoneinfo/Europe/Berlin
export TZ=/usr/share/zoneinfo/America/New_York
```

**Comment by hustcc** [comment]
So we should set the env before execute the testcases?
